allowBuilds:
  '@parcel/watcher': true
  '@swc/core': true
  esbuild: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - '@pormeldev/axis-client-kit@0.9.0 || 0.9.1-beta.0'
  - '@pormeldev/axis-design-system@2.48.0'
  - '@pormeldev/axis-shared@0.7.0'
  - '@pormeldev/axis-tw-theme-default@1.10.0'
  - '@pormeldev/next-runtime-kit@1.5.1'
